prompt="If you share your name, we can personolize the message"
prompt+="\nwhat is your name"
name = input(prompt)
print(f"\nHello, {name}!")
print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 100.")
print("Can you guess it?")
print("Please enter a number between 1 and 100.")
print("If you want to exit the game, type 'exit'.")
print("If you want to see the rules, type 'rules'.")
print("If you want to see the leaderboard, type 'leaderboard'.")
print("If you want to see the instructions, type 'instructions'.")
print("If you want to see the credits, type 'credits'.")
print("If you want to see the settings, type 'settings'.")
print("If you want to see the help, type 'help'.")
print("If you want to see the about, type 'about'.")
print("If you want to see the contact, type 'contact'.")