#place to visit
places=["mekke","medine","tokyo","londra","mugla"]
print("Original order:")
print(places)
print("\nAlphabetical order:")
print(sorted(places))
print("\nOriginal order:")
print(places)
print("\nTers Alphatebital order:")
print(sorted(places, reverse=True))
print("\nOriginal order:")
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
print(len(places))